export class Securityequity {
    ID :Number;
    SecurityName :String;
    SecurityDescription :String;
    HasPosition :String;
    ActiveSecurity :String;
    LotSize :Number;
    BBGUniqueName : String;
    CUSIP :String;
    ISIN  :String;
    SEDOL  :String;
    BBGTicker:String;
    BBGUID :String;
    BBGGlobalID :String;
    TickerAndExchange : String;
    ADRFlag : String;
    ADRUnderlyingTicker : String;
    ADRUnderlyingCurrency : String;
    SharesPerADR : Float32Array;
    IPODate : Date;
    PricingCurrency : String;
    SettleDays : Number;
    OutstandingShares : Float32Array;
    VotingRightsPerShare : Float32Array;
    AverageVolume : Float32Array;
    Beta : Float32Array;
    ShortInterest : Float32Array;
    ReturnYTD : Float32Array;
    Volatility : Float32Array;
    AssetClass : String;
    PFCountry : String;
    PFCreditRating : String;
    PFCurrency : String;
    PFInstrument : String; 
    PFLiquidityProfile : String;
    PFMaturity : Date;
    PFNAICSCode : String;
    PFRegion : String;
    PFSector : String;
    PFSubAssetClass : String;
    CountryOfIssuance: String
    Exchange : String;
    IssuerName  : String;
    IssueCurrency  : String;
    TradingCurrency  : String;
    BBGIndustrySubGroup  : String;
    BBGIndustryGroup  : String;
    BBGSector : String;
    CountryOfIncorporation : String;
    RiskCurrency : String;
    OpenPrice : Float32Array;
    ClosePrice : Float32Array;
    Volume : Float32Array;
    LastPrice : Float32Array;
    AskPrice : Float32Array;
    BidPrice : Float32Array;
    PERatio : Float32Array;
    DividendDeclareDate : Date;
    DividendExDate : Date ;
    DividendRecordDate : Date;
    DividendPayDate : Date;
    DividendAmount : Number;
    Frequency : String;
    DividendType : String;
}
