export class Securityequity {
    ID :Number;
    SecurityName :String;
    SecurityDescription :String;
    HasPosition :String;
    ActiveSecurity :String;
    LotSize :Number;
    BBGUniqueName : String;
    CUSIP :String;
    ISIN  :String;
    SEDOL  :String;
    BBGTicker:String;
    BBGUID :String;
    BBGGlobalID :String;
    TickerAndExchange : String;
    ADRFlag : String;
    ADRUnderlyingTicker : String;
    ADRUnderlyingCurrency : String;
    SharesPerADR :number;
    IPODate : string;
    PricingCurrency : String;
    SettleDays : Number;
    OutstandingShares : number;
    VotingRightsPerShare : number;
    AverageVolume : number;
    Beta : number;
    ShortInterest : number;
    ReturnYTD : number;
    Volatility : number;
    AssetClass : String;
    PFCountry : String;
    PFCreditRating : String;
    PFCurrency : String;
    PFInstrument : String; 
    PFLiquidityProfile : String;
    PFMaturity : string;
    PFNAICSCode : String;
    PFRegion : String;
    PFSector : String;
    PFSubAssetClass : String;
    CountryOfIssuance: String
    Exchange : String;
    IssuerName  : String;
    IssueCurrency  : String;
    TradingCurrency  : String;
    BBGIndustrySubGroup  : String;
    BBGIndustryGroup  : String;
    BBGSector : String;
    CountryOfIncorporation : String;
    RiskCurrency : String;
    OpenPrice : number;
    ClosePrice : number;
    Volume : number;
    LastPrice : number;
    AskPrice : number;
    BidPrice : number;
    PERatio : number;
    DividendDeclareDate : string;
    DividendExDate : string ;
    DividendRecordDate : string;
    DividendPayDate : string;
    DividendAmount : Number;
    Frequency : String;
    DividendType : String;
}
