export class Securityequity {
    ID :number;
    SecurityName :string;
    SecurityDescription :string;
    HasPosition :string;
    ActiveSecurity :string;
    LotSize :number;
    BBGUniqueName : string;
    CUSIP :string;
    ISIN  :string;
    SEDOL  :string;
    BBGTicker:string;
    BBGUID :string;
    BBGGlobalID :string;
    TickerAndExchange : string;
    ADRFlag : string;
    ADRUnderlyingTicker : string;
    ADRUnderlyingCurrency : string;
    SharesPerADR : number;
    IPODate : string;
    PricingCurrency : string;
    SettleDays : number;
    OutstandingShares : number;
    VotingRightsPerShare : number;
    AverageVolume : number;
    Beta : number;
    ShortInterest : number;
    ReturnYTD : number;
    Volatility : number;
    AssetClass : string;
    PFCountry : string;
    PFCreditRating : string;
    PFCurrency : string;
    PFInstrument : string; 
    PFLiquidityProfile : string;
    PFMaturity : string;
    PFNAICSCode : string;
    PFRegion : string;
    PFSector : string;
    PFSubAssetClass : string;
    CountryOfIssuance: string;
    Exchange : string;
    IssuerName  : string;
    IssueCurrency  : string;
    TradingCurrency  : string;
    BBGIndustrySubGroup  : string;
    BBGIndustryGroup  : string;
    BBGSector : string;
    CountryOfIncorporation : string;
    RiskCurrency : string;
    OpenPrice : number;
    ClosePrice : number;
    Volume : number;
    LastPrice : number;
    AskPrice : number;
    BidPrice : number;
    PERatio : number;
    DividendDeclareDate : string;
    DividendExDate : string ;
    DividendRecordDate : string;
    DividendPayDate : string;
    DividendAmount : number;
    Frequency : string;
    DividendType : string;
}
