export class Securitybond {
    ID :number;
    SecurityDescription:string;
  SecurityName :string;
 AssetType :string;
  InvestmentType:string;
  TradingFactor :string;
  PricingFactor :string;
 ISIN:string;
  BBGTicker :string;
   BBGUniqueID :string;
    SEDOL:string;
    FirstCouponDate:string;
 Cap:string;
  FloorValue:string;
   CouponFrequency :string;
     Coupon :string;
     CouponType :string;
    Spread :string;
      CallableFlag :string;
   FixtoFloatFlag:string;
   PutableFlag :string;
  IssueDate:string;
  LastResetDate :string;
    Maturity:string;
  CallNotificationMaxDays:string;
 PutNotificationMaxDays:string;
   PenultimateCouponDate :string;
   ResetFrequency :string;
    HasPosition :string;
 MacaulayDuration :string;
    Volatility_30D :string;
     Volatility_90D :string;
     Convexity :string;
      AverageVolume_30Day:string; 
      PFAssetClass :string;
     PFCountry :string;
      PFCreditRating :string;
    PFCurrency :string;
     PFInstrument :string;
      PFLiquidityProfile :string;
      PFMaturity:string;
     PFNAICSCode:string;
     PFRegion:string;
      PFSector :string;
      PFSubAssetClass :string;
    BloombergIndustryGroup :string;
     BloombergIndustrySubGroup:string;
    BloombergIndustrySector:string;
     CountryofIssuance :string;
 IssueCurrency :string;
    IssuerName:string;
     RiskCurrency :string;
    PutDate :string;
   PutPrice :string; 
     AskPrice :string; 
      HighPrice :string; 
      LowPrice :string; 
   OpenPrice :string; 
    Volume :string; 
    BidPrice :string; 
     LastPrice :string; 
     CallDate :string;
     CallPrice :string; 
}
 